env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - prettier
plugins:
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  {  "@typescript-eslint/return-await": "off" }
