import { ArticleEntity } from "@src/core/article/article.schema";

export const articlesMock: ArticleEntity[] = [
  {
    id: 1,
    title: "寂静海洋中的歌声",
    body: "一本描绘深海中神秘生物与海洋奥秘的小说，通过主人公的探险旅程，展现了一个宁静而生动的海底世界。",
    author: "赵六",
    author_id: 1,
    order: 1,
    book: "晨光下的诺言",
    book_id: 1,
    love: false,
  },
  {
    id: 2,
    title: "时空旅者的日记",
    body: "描绘了一位穿梭于不同历史时期的旅行者的故事，书中记录了他见证的古代文明兴衰和未来世界的变迁，是一次跨越时空的精彩冒险。",
    author: "李四",
    author_id: 2,
    order: 1,
    book: "影之谷的秘密",
    book_id: 2,
    love: false,
  },
  {
    id: 3,
    title: "古代人的故事",
    body: "描绘了一位古代人的故事，以及他们在古代文明中的生活方式。",
    author: "李四",
    author_id: 2,
    order: 1,
    book: "风之谷的回声",
    book_id: 3,
    love: false,
  },
  {
    id: 4,
    title: "古代人的故事2",
    body: "描绘了一位古代人的故事，和他们的工作。",
    author: "李四",
    author_id: 2,
    order: 2,
    book: "风之谷的回声",
    book_id: 3,
    love: false,
  },
];
