name: library
on: push
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run check
      - run: bunx prisma migrate deploy
      - run: bun run test
    env:
      DATABASE_URL: "file:../ci.db"
